parallel-jobs = 1
logging-to-file = true        # enables logging of every patch process to a seperate file
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

[Twitter]
build-mode = "apk"
uptodown-dlurl = "https://twitter.en.uptodown.com/android"

[Twitch]
uptodown-dlurl = "https://twitch-app.en.uptodown.com/android"

[TikTok]
uptodown-dlurl = "https://tiktok.en.uptodown.com/android"

[Reddit]
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"

[Lightroom]
enabled = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/adobe/lightroom/"
apkmirror-arch = "arm64-v8a + x86_64"

[Messenger]
enabled = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/messenger/"
apkmirror-arch = "arm64-v8a"

[Spotify]
enabled = true
uptodown-dlurl = "https://spotify.en.uptodown.com/android"

[Citra]
enabled = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/citra-emulator/citra-emulator/"
apkmirror-arch = "arm64-v8a"

[Backdrops]
enabled = true
uptodown-dlurl = "https://backdrops.en.uptodown.com/android"

[WarnWetter]
enabled = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/deutscher-wetterdienst/warnwetter/"

[Windyapp]
enabled = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/windy-weather-world-inc/windy-wind-weather-forecast/"

[IconPackStudio]
enabled = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/smart-launcher-team/icon-pack-studio/"

[TickTick]
enabled = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/appest-inc/ticktick-to-do-list-with-reminder-day-planner/"
apkmirror-arch = "arm64-v8a"

[Tasker]
enabled = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/joaomgcd/tasker/"

[Photomath]
enabled = false
apkmonk-dlurl = "https://www.apkmonk.com/app/com.microblink.photomath/"

[NovaLauncher]
enabled = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/teslacoil-software/nova-launcher/"

[NetGuard]
enabled = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/marcel-bokhorst/netguard-no-root-firewall/"

[IrPlus]
enabled = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/binarymode/irplus-infrared-remote/"

[Instagram]
enabled = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/instagram-instagram/"
apkmirror-arch = "arm64-v8a"

[MyExpenses]
enabled = true
uptodown-dlurl = "https://my-expenses.en.uptodown.com/android"

[NyxMusicPlayer]
enabled = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/awedea/nyx-music-player/"
apkmirror-arch = "arm64-v8a"

[VSCO]
enabled = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/vsco/vsco-cam/"

[CandyLinkVPN]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/liondev-io/candylink-vpn/"
apkmirror-arch = "arm64-v8a"

[SyncForReddit]
enabled = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/red-apps-ltd/sync-for-reddit/"
integrations-source = "revanced/revanced-integrations"
